all:
  vars:
    ansible_python_interpreter: /opt/miniconda3/bin/python3
  children:
    cisco_routers:
      hosts:
        JLM-LAB-R1:
          ansible_host: 192.168.10.1
          ansible_user: admin
          ansible_password: "{{ router_password }}"
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_become: false
          ansible_paramiko_host_key_auto_add: true
    cisco_switches:
      hosts:
        JLM-LAB-SW1:
          ansible_host: 192.168.99.2
          ansible_user: admin
          ansible_password: "{{ switch_password }}"
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_become: false
          ansible_paramiko_host_key_auto_add: true
